### ISSUE TITLE
Firmware

### ISSUE THREAD

**Issue by thbreidenbach** [mlorenzati/pico-rgb2hdmi#37]
Hey, could you elaborate on the firmware release? The Binaries include several test u2f but I'm asking myself which is the exact firmware.
I just finished my build an hopefully it'll work.

**Comment by mlorenzati** [comment]
Sure, there package has different test for the submodules, the one you want for RGB2HDMI is the integrationtest.uf2
Please start validating HDMI works (check the Resistor array is are not tied to each other or to ground), then check AFE.
If youc can validate with microscope the pins on the AFE and clean througfully solder flux since it affects the capture.

**Comment by thbreidenbach** [comment]
Great, Thank! I upladed the integrationtest firmware and can successfully see the menu. Colors are washed out greatly which might be an issue with the used WM8214. Will start working on a db23 adapter and test on!! 
Maybe you could collect the different sources of information (PCBWay, Google, etc.) here? I will assemble information for a1k.org and will give some assembled boards to testers there. Is there something to keep in mind regarding the WM8214 whilest troubleshooting?

**Comment by mlorenzati** [comment]
I do need to complete what I started in https://github.com/mlorenzati/pico-rgb2hdmi/tree/gain_offset_options to allow offset and gain per RGB to manage the color differences due to timing between WM8213 and WM8214.
Also could be possible to tweak the timing on the pio capture program but that would be an overkill IMO.
If colors are shifted that's the wm8412 timing, if washed is more related to flux messing with an unwanted rc profile

**Comment by thbreidenbach** [comment]
Hi, I get really bad sync and colors are way off which will be an issue of the wm8214. At first the picture is extremely dim ´. With gain and offset this can be partially solved but blue seems to be mostly missing. Would it be possible to output a dedicated test image on the host computer and let the pi calculate offset and gain per rgb?

**Comment by mlorenzati** [comment]
Bad sync can be multiple things, please check videos on yt about how it looks like as for today, since video has some glitches that has to be managed on firmware but not extreme.
To validate you have a clean WM8214, (as I said clean with iso and toothbrush and clean with hot air on 200-240 degrees.

Finally, set video capture on 320x240 to  see how it looks, if better you have pending dirt.
I still need to complete manual per RGB gain and offset, no time to complete it yet.

**Comment by ottifant011** [comment]
I have built myself a Pico RGB2HDMI.
How can I programme it under windows? Is there a manual for beginners?

**Comment by thbreidenbach** [comment]
Usually one just connects the RPi Pico to the windows computer and drags the fw file in the newly added drive (which represents the pi) which firmware you need can be seen in this thread. (integrationtest.uf2)
Which Chip do you use? WM8213 or WM8214?

**Comment by ottifant011** [comment]
hm i have already done that but nothing is happening, no image output no flashing led nothing.
I only got the WM8214

**Comment by ottifant011** [comment]
if i de-energise the pico it seems to be empty again u2f file no longer there

**Comment by ottifant011** [comment]
> @ottifant011, können Sie zunächst einmal ausprobieren `hdmiTest.uf2`. Das sollte einiges über den HDMI-Anschluss senden. Und denken Sie daran, dass sich der Pico im Massenspeichermodus befinden MUSS, um eine UF2-Datei darauf übertragen zu können. Halten Sie dazu die BOOTSEL-Taste gedrückt und schließen Sie dann den Pico an. Lassen Sie dann die BOOTSEL-Taste los.

das hab ich schon probiert das geht leider auch nichts bzw. kein HDMI Signal

**Comment by ottifant011** [comment]
what i don't understand it is immediately recognised as a drive without me having to press a button

**Comment by thbreidenbach** [comment]
Why wouldn’t it? That’s how it’s built.

**Comment by mlorenzati** [comment]
@ottifant011, to burn the firmware into the device
- press RESET
- press BOOT
- release RESET
That should show the pen drive option on the computer

Start with the simple HDMI demo, test it in monitors with DVI back compatibility, TVs is more likely not to work with that firm.

HDMI support has to be integrated from what I built in https://github.com/mlorenzati/PicoDVI

**Comment by ottifant011** [comment]
i just can't get a picture output, a monitor says outside the working area

**Comment by charlysan** [comment]
@ottifant011, have you tried using a different monitor? My monitor experiences issues at certain resolutions, however, `hdmiTest.uf2` has always worked. What about your Pico? Have you checked to ensure it's working well?

**Comment by charlysan** [comment]
I've just checked using `hdmiTest.uf2` from `pico-rgb2hdmi-0.6.3.zip` and it works as expected. I followed the [instructions](https://github.com/mlorenzati/pico-rgb2hdmi/issues/37#issuecomment-1917983604) from Marcelo.

**Comment by ottifant011** [comment]
tomorrow i will build a new one piece by piece, for HDMI test picture you don't need an input circuit with ic's.
I'm building the Beta3 but that shouldn't matter, maybe the chinese have delivered with it.
Do all HDMI sockets have the same pinout? not that's where the fault lies

**Comment by ottifant011** [comment]
> I've just checked using `hdmiTest.uf2` from [pico-rgb2hdmi-0.6.3.zip](https://github.com/mlorenzati/pico-rgb2hdmi/releases/download/0.6.3/pico-rgb2hdmi-0.6.3.zip) and it works as expected. I followed the [instructions](https://github.com/mlorenzati/pico-rgb2hdmi/issues/37#issuecomment-1917983604) from Marcelo.
> 
> And BTW, this also works for me:
> 
>     1. press BOOT and hold
> 
>     2. press RESET
> 
>     3. release BOOT

I did it exactly the same way and no test image appears even when rebuilding

![WhatsApp Bild 2024-02-01 um 18 05 40_78669cde](https://github.com/mlorenzati/pico-rgb2hdmi/assets/149962813/d367fcce-4c87-4b90-b0f8-5ce25923c6f2)

**Comment by charlysan** [comment]
> > I've just checked using `hdmiTest.uf2` from [pico-rgb2hdmi-0.6.3.zip](https://github.com/mlorenzati/pico-rgb2hdmi/releases/download/0.6.3/pico-rgb2hdmi-0.6.3.zip) and it works as expected. I followed the [instructions](https://github.com/mlorenzati/pico-rgb2hdmi/issues/37#issuecomment-1917983604) from Marcelo.
> > And BTW, this also works for me:
> > ```
> > 1. press BOOT and hold
> > 
> > 2. press RESET
> > 
> > 3. release BOOT
> > ```
> 
> I did it exactly the same way and no test image appears even when rebuilding
> 
> ![WhatsApp Bild 2024-02-01 um 18 05 40_78669cde](https://private-user-images.githubusercontent.com/149962813/301586799-d367fcce-4c87-4b90-b0f8-5ce25923c6f2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MDc4NzYsIm5iZiI6MTcwNjgwNzU3NiwicGF0aCI6Ii8xNDk5NjI4MTMvMzAxNTg2Nzk5LWQzNjdmY2NlLTRjODctNGI5MC1iMGY4LTVjZTI1OTIzYzZmMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQxNzEyNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzVmMzkzMzVkMjI0M2VkMGExYmNlZjlhYWQzMTA3MTI2ODBlMGJjNDhkMmUwYWU0MWYzOGMzMzc1ZTE3YzMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7YFE4ix-PWzezQgQ-6IIxgcgcGAIZwBrrHVDyjxI_hg)

@ottifant011, I recommend opening a new issue titled 'No HDMI Output' for a detailed discussion on this problem, since the current thread is specifically for clarifying aspects of the firmware release.

And considering that the main question in this discussion has been resolved, I am now closing this issue.

cc: @mlorenzati
